### ISSUE TITLE
Crash when trying to open advanced menu

### ISSUE THREAD

**Issue by coolnickname** [ellenhebert/Grappl#14]
When I open Grappl it opens twice for some reason and when I enter a port it say's it can't connect to the relay server. When I try to open the advanced menu it crashen and when I open the console I get this log:
`[25-apr-2016 12:16:10] Started: Grappl Beta 1.5.10 {Brand=DaexsysVanilla, Mode=GUI}
[25-apr-2016 12:16:10] JVM version: 1.8.0_91 | OS: Windows 7 | Arch: amd64
[25-apr-2016 12:16:10] If you encounter issues, please report them to @grapplstatus, or @Cactose.
[25-apr-2016 12:16:10] Preferably with a copy of this log! Thx <3
[25-apr-2016 12:16:10] ====================
[25-apr-2016 12:16:10] Preparing to load plugins-
[25-apr-2016 12:16:10] 0 plugin(s) loaded
[25-apr-2016 12:16:10] ====================
[25-apr-2016 12:16:11] Password is null
[25-apr-2016 12:16:11] Exception in thread "Thread-0" 
[25-apr-2016 12:16:11] java.lang.NullPointerException
[25-apr-2016 12:16:11] 	at io.grappl.client.impl.relay.RelayServer.ping(RelayServer.java:60)
[25-apr-2016 12:16:11] 	at io.grappl.client.impl.relay.RelayManager.offerRelay(RelayManager.java:12)
[25-apr-2016 12:16:11] 	at io.grappl.client.impl.ApplicationState$1.run(ApplicationState.java:34)
[25-apr-2016 12:16:11] 	at java.lang.Thread.run(Unknown Source)
[25-apr-2016 12:16:11] Password is null
[25-apr-2016 12:16:11] Grappl Command Line (type a command, or type 'help' or 'help [command]' for ideas!)
[25-apr-2016 12:16:13] Creating grappl connection 295759c2-852c-495f-a8c3-302aeaee7dda
[25-apr-2016 12:16:13] Auth connection created 66530616-0143-49f2-b8e4-040daff6a841
[25-apr-2016 12:16:14] Exiting
[25-apr-2016 12:16:14] No state
[25-apr-2016 12:16:16] Exception in thread "AWT-EventQueue-0" 
[25-apr-2016 12:16:16] java.lang.NumberFormatException: For input string: ""
[25-apr-2016 12:16:16] 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[25-apr-2016 12:16:16] 	at java.lang.Integer.parseInt(Unknown Source)
[25-apr-2016 12:16:16] 	at java.lang.Integer.parseInt(Unknown Source)
[25-apr-2016 12:16:16] 	at io.grappl.gui.DefaultGUI$7.actionPerformed(DefaultGUI.java:223)
[25-apr-2016 12:16:16] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[25-apr-2016 12:16:16] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[25-apr-2016 12:16:16] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[25-apr-2016 12:16:16] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[25-apr-2016 12:16:16] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Component.processMouseEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Component.processEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Container.processEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Component.dispatchEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.Component.dispatchEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventQueue.access$500(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventQueue$3.run(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventQueue$3.run(Unknown Source)
[25-apr-2016 12:16:16] 	at java.security.AccessController.doPrivileged(Native Method)
[25-apr-2016 12:16:16] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[25-apr-2016 12:16:16] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventQueue$4.run(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventQueue$4.run(Unknown Source)
[25-apr-2016 12:16:16] 	at java.security.AccessController.doPrivileged(Native Method)
[25-apr-2016 12:16:16] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[25-apr-2016 12:16:16] 	at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by coolnickname** [comment]
I know I should have tried this before but the .jar version works fine. So this only happends with the windows version.
I'll leave the issue open in case you still want to fix it, but I dont need it anymore ^-^

**Comment by ellenhebert** [comment]
Just encountered this issue as well (I think). Interestingly, it was on the mac version.
