### ISSUE TITLE
Grappl Not Working.

### ISSUE THREAD

**Issue by Syntist** [ellenhebert/Grappl#24]
I am Using Arch Linux.

I have build it, but can't use it.
only one server n.grappl.io which is unreachable.

Thats the Out When using "Run Without Logging In"

[Jan 1, 2017 4:39:36 AM] Launcher version: 1.0
[Jan 1, 2017 4:39:36 AM] Started: Grappl Beta 1.6.6 {Brand=DaexsysVanilla, Mode=GUI}
[Jan 1, 2017 4:39:36 AM] JVM version: 1.8.0_112 | OS: Linux | Arch: amd64
[Jan 1, 2017 4:39:36 AM] If you encounter issues, please report them to @grapplstatus, or ellenhbrt@gmail.com.
[Jan 1, 2017 4:39:36 AM] Preferably with a copy of this log! Thx <3
[Jan 1, 2017 4:39:36 AM] ====================
[Jan 1, 2017 4:39:36 AM] Preparing to load plugins-
[Jan 1, 2017 4:39:36 AM] ====================
[Jan 1, 2017 4:39:36 AM] Password is null
[Jan 1, 2017 4:40:22 AM] Password is null
[Jan 1, 2017 4:40:24 AM] Creating grappl connection 9167f414-bd21-45cd-bf56-86feddf9460c
[Jan 1, 2017 4:40:24 AM] Auth connection created cdeb6c80-0a58-40d8-bd2c-e6c5dc0c1e68
[Jan 1, 2017 4:40:25 AM] No state

And Advanced Output
[Jan 1, 2017 4:40:55 AM] Launcher version: 1.0
[Jan 1, 2017 4:40:55 AM] Started: Grappl Beta 1.6.6 {Brand=DaexsysVanilla, Mode=GUI}
[Jan 1, 2017 4:40:55 AM] JVM version: 1.8.0_112 | OS: Linux | Arch: amd64
[Jan 1, 2017 4:40:55 AM] If you encounter issues, please report them to @grapplstatus, or ellenhbrt@gmail.com.
[Jan 1, 2017 4:40:55 AM] Preferably with a copy of this log! Thx <3
[Jan 1, 2017 4:40:55 AM] ====================
[Jan 1, 2017 4:40:55 AM] Preparing to load plugins-
[Jan 1, 2017 4:40:55 AM] ====================
[Jan 1, 2017 4:40:55 AM] Password is null
[Jan 1, 2017 4:41:27 AM] Creating grappl connection a99b2623-8915-4b8f-9e87-a9583adfc8e7
[Jan 1, 2017 4:41:28 AM] Connection opened: relayserver=n.grappl.io localport=27015
[Jan 1, 2017 4:41:28 AM] Hosting on: n.grappl.io:7355
[Jan 1, 2017 4:41:29 AM] Connected to heartbeat server @ n.grappl.io

Still my friend wasn't able to connect me.

**Comment by ellenhebert** [comment]
How does it work when logged in? I've noticed the "Run without logging in" mode seems to be somewhere between temperamental and non-functional.

**Comment by ellenhebert** [comment]
Also, if you're on linux and have python3 installed, you may want to consider the python version, which is for the command line. It's more lightweight and terminal oriented.

https://github.com/ellenhebert/Grappy

**Comment by Syntist** [comment]
Where to Create an account? Site is down can't create account. 
I Think its not working because i am having high ping. 

```
PING n.grappl.io (104.236.65.204) 56(84) bytes of data.
64 bytes from n.grappl.io (104.236.65.204): icmp_seq=1 ttl=51 time=421 ms
64 bytes from n.grappl.io (104.236.65.204): icmp_seq=2 ttl=51 time=431 ms
64 bytes from n.grappl.io (104.236.65.204): icmp_seq=3 ttl=51 time=425 ms
64 bytes from n.grappl.io (104.236.65.204): icmp_seq=4 ttl=49 time=435 ms
64 bytes from n.grappl.io (104.236.65.204): icmp_seq=5 ttl=51 time=427 ms
64 bytes from n.grappl.io (104.236.65.204): icmp_seq=6 ttl=49 time=425 ms
64 bytes from n.grappl.io (104.236.65.204): icmp_seq=7 ttl=49 time=431 ms

```

And Python Gappry Also not working.

PyGrappl Alpha 1 ✦ | Created by Ellen Hebert | @liloqueue
By using this application, you accept the terms of service laid out in the github repository. In short, you will not do anything illegal with this service, and you are responsible for all use. Any part of the service may go down at any time. This program is licensed under the LGPL v2.1.
Type YES if you agree.
YES
Do tell, what port is your server running on?
27015
Attempting to tunnel through localhost to localhost:27015.
Traceback (most recent call last):
  File "./grappl.py", line 54, in <module>
    connectToRelay(domain, port)
  File "./grappl.py", line 16, in connectToRelay
    messageConnection = s.connect((relay, message_port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by ellenhebert** [comment]
That's definitely strange, I can't replicate the thing with the python script either. I suppose it's not impossible that the relay server might be refusing connections because of ping, but I don't think I ever wrote the timeouts to be that short.

**Comment by ellenhebert** [comment]
OH wait. Just found a bug in the Grappy code. Going to push a fix.

**Comment by Syntist** [comment]
Still same

```
By using this application, you accept the terms of service laid out in the github repository. In short, you will not do anything illegal with this service, and you are responsible for all use. Any part of the service may go down at any time. This program is licensed under the LGPL v2.1.
Type YES if you agree.
YES
Do tell, what port is your server running on?
27015
What relay server would you like to use? {default is n.grappl.io}
n.grappl.io
Attempting to tunnel through n.grappl.io to localhost:27015.
Connected to message server. Protocol version: 2
Hosting on n.grappl.io:390
A user has connected from ip \
Traceback (most recent call last):
  File "./grappl.py", line 55, in <module>
    connectToRelay(server, port)
  File "./grappl.py", line 30, in connectToRelay
    transmissionExternal.connect((relay, transmissionPort))
ConnectionRefusedError: [Errno 111] Connection refused

```
